var userNames;
var workersNameId;
var studentsNames;
var userId;
userNames = ["sharif", "rabu", "pinky", "arif"];
studentsNames = ["lovley", "Lucky", "lovelu"];
userId = [2, 5, 7, 9, 8, 3];
console.log(userNames);
console.log(userId);
console.log(userId.sort());
console.log(userNames);
console.log(userNames.sort());
